name: generate and push webp image version
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      - name: Check if there are any changes
        id: changed-files-specific
        uses: tj-actions/changed-files@v41
        with:
          files: |
            kamitainet/*

      - name: Setup cwebp
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          pwd
          sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libgif-dev
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.3.2-linux-x86-64.tar.gz
          tar xzvf libwebp-1.3.2-linux-x86-64.tar.gz
          cd libwebp-1.3.2-linux-x86-64/bin
          mv cwebp ${{ github.workspace }}
          cd ../..
          rm -rf libwebp-1.3.2-linux-x86-64
          rm -rf libwebp-1.3.2-linux-x86-64.tar.gz
          sudo mv cwebp /bin
          ls

      - name: bash file to create the webp version of the images
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
         bash webp.sh /kamitainet/