name: profile-update-actions
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./kamitainet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python main.py
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Change image to webp