name: profile-update-actions
on:
  push:
    paths:
    - 'kamitainet/**'
jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kamitainet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Run
        run: |
          pip install -r requirements.txt
          python main.py